#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt',
   :git => 'https://github.com/fnichol/chef-apt'
cookbook 'git',
  :git => 'https://github.com/fnichol/chef-git.git'
cookbook 'mysql',
  :git => 'git://github.com/opscode-cookbooks/mysql.git'
cookbook 'apparmor',
  :git => 'git://github.com/opscode-cookbooks/apparmor.git'
cookbook 'build-essential'
cookbook 'database',
  :git => 'git://github.com/opscode-cookbooks/database.git'
